language: ruby
script: bundle exec rake
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
gemfile:
 - Gemfile.activerecord2
 - Gemfile.activerecord3
before_script:
  - psql -c 'create database scoped_search_test;' -U postgres
  - mysql -e 'create database scoped_search_test;'
