language: ruby
cache: bundler
sudo: false

install:
- bundle install
before_script:
- psql -c 'create database scoped_search_test;' -U postgres
- mysql -e 'create database scoped_search_test;'
script:
- bundle exec rake

rvm:
- "1.9"
- "2.0"
- "2.1"
- "2.2"
- ruby-head
- jruby-19mode
- jruby-head

gemfile:
- Gemfile.activerecord32
- Gemfile.activerecord40
- Gemfile.activerecord41
- Gemfile.activerecord42

matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
