language: ruby
script: bundle exec rake
before_script:
  - psql -c 'create database scoped_search_test;' -U postgres
  - mysql -e 'create database scoped_search_test;'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - jruby-19mode
  - jruby-head
gemfile:
 - Gemfile.activerecord3
 - Gemfile.activerecord40
 - Gemfile.activerecord41
matrix:
  include:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
