language: ruby
cache: bundler
sudo: false

install:
- bundle install
before_script:
- psql -c 'create database scoped_search_test;' -U postgres
- mysql -e 'create database scoped_search_test;'
script:
- bundle exec rake

rvm:
- "2.0"
- "2.1"
- "2.2.2"
- "2.3.1"
- ruby-head
- jruby-19mode
- jruby-head

gemfile:
- Gemfile.activerecord32
- Gemfile.activerecord40
- Gemfile.activerecord41
- Gemfile.activerecord42
- Gemfile.activerecord50

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
  exclude:
    - rvm: "2.0"
      gemfile: Gemfile.activerecord50
    - rvm: "2.1"
      gemfile: Gemfile.activerecord50
    - rvm: "2.3.1"
      gemfile: Gemfile.activerecord32
