language: ruby
script: bundle exec rake
before_script:
  - psql -c 'create database scoped_search_test;' -U postgres
  - mysql -e 'create database scoped_search_test;'
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
gemfile:
 - Gemfile.activerecord2
 - Gemfile.activerecord3
 - Gemfile.activerecord4
matrix:
  include:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 2.0.0
      gemfile: Gemfile.activerecord2
    - rvm: 2.1.1
      gemfile: Gemfile.activerecord2
  exclude:
    - rvm: jruby-18mode
      gemfile: Gemfile.activerecord2
    - rvm: jruby-19mode
      gemfile: Gemfile.activerecord2
    - rvm: jruby-head
      gemfile: Gemfile.activerecord2
    - rvm: 1.8.7
      gemfile: Gemfile.activerecord4
    - rvm: jruby-18mode
      gemfile: Gemfile.activerecord4
